package okienka;

import javax.swing.JOptionPane;

public class Pizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizza
     */
    public Pizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jRadioButtonCienkie = new javax.swing.JRadioButton();
        jRadioButtonGrube = new javax.swing.JRadioButton();
        jRadioButtonSrednie = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelSkladniki = new javax.swing.JLabel();
        jCheckBoxSer = new javax.swing.JCheckBox();
        jCheckBoxSzynka = new javax.swing.JCheckBox();
        jCheckBoxPieczarki = new javax.swing.JCheckBox();
        jCheckBoxPapryka = new javax.swing.JCheckBox();
        jCheckBoxOliwki = new javax.swing.JCheckBox();
        jCheckBoxSalami = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabelCiasto = new javax.swing.JLabel();
        jComboBoxCiasto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Zamów");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 162, -1));

        jRadioButtonCienkie.setText("cienkie");
        jPanel7.add(jRadioButtonCienkie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jRadioButtonGrube.setText("grube");
        jPanel7.add(jRadioButtonGrube, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jRadioButtonSrednie.setText("średnie");
        jRadioButtonSrednie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSrednieActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButtonSrednie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel3.setText("Ciasto");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 47, -1, -1));

        jLabelSkladniki.setText("Składniki");

        jCheckBoxSer.setText("ser");

        jCheckBoxSzynka.setText("szynka");

        jCheckBoxPieczarki.setText("pieczarki");

        jCheckBoxPapryka.setText("papryka");

        jCheckBoxOliwki.setText("oliwki");

        jCheckBoxSalami.setText("salami");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabelSkladniki)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxSalami)
                                .addComponent(jCheckBoxSzynka)
                                .addComponent(jCheckBoxSer)
                                .addComponent(jCheckBoxPieczarki)
                                .addComponent(jCheckBoxPapryka)
                                .addComponent(jCheckBoxOliwki))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jCheckBoxSer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxSzynka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jCheckBoxPieczarki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxPapryka)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabelSkladniki)
                                        .addGap(21, 21, 21)))
                        .addComponent(jCheckBoxOliwki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxSalami)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCiasto.setText("Rozmiar pizzy");

        jComboBoxCiasto.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"mała", "średnia", "duża"}));
        jComboBoxCiasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiastoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabelCiasto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCiasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxCiasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCiasto))
                        .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCiastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiastoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String rozmiarPizzy = "";
        String skladniki = "";
        String ciasto = "";

        if (jComboBoxCiasto.getSelectedItem().toString().equals("mała")) {
            rozmiarPizzy = "mały";
        }

        if (jComboBoxCiasto.getSelectedItem().toString().equals("duża")) {
            rozmiarPizzy = "duży";
        }

        if (jComboBoxCiasto.getSelectedItem().toString().equals("średnia")) {
            rozmiarPizzy = "średni";
        }

        if (jCheckBoxSer.isSelected()) {
            skladniki += jCheckBoxSer.getText() + ", ";
        }
        if (jCheckBoxSzynka.isSelected()) {
            skladniki += jCheckBoxSzynka.getText() + ", ";
        }

        if (jCheckBoxPieczarki.isSelected()) {
            skladniki += jCheckBoxPieczarki.getText() + ", ";
        }

        if (jCheckBoxPapryka.isSelected()) {
            skladniki += jCheckBoxPapryka.getText() + ", ";
        }

        if (jCheckBoxOliwki.isSelected()) {
            skladniki += jCheckBoxOliwki.getText() + ", ";
        }

        if (jCheckBoxSalami.isSelected()) {
            skladniki += jCheckBoxSalami.getText() + ", ";
        }

        if (jRadioButtonCienkie.isSelected()) {
            ciasto += jRadioButtonCienkie.getText();

        } else if (jRadioButtonGrube.isSelected()) {
            ciasto += jRadioButtonGrube.getText();

        } else {
            ciasto += jRadioButtonSrednie.getText();
        }

        JOptionPane.showMessageDialog(this,
                "Zamówiona pizza: rozmiar " + rozmiarPizzy + ", " + "ciasto " + ciasto + ", " + "składaniki: " + skladniki,
                "Zamówienie",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonSrednieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSrednieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSrednieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxOliwki;
    private javax.swing.JCheckBox jCheckBoxPapryka;
    private javax.swing.JCheckBox jCheckBoxPieczarki;
    private javax.swing.JCheckBox jCheckBoxSalami;
    private javax.swing.JCheckBox jCheckBoxSer;
    private javax.swing.JCheckBox jCheckBoxSzynka;
    private javax.swing.JComboBox jComboBoxCiasto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCiasto;
    private javax.swing.JLabel jLabelSkladniki;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonCienkie;
    private javax.swing.JRadioButton jRadioButtonGrube;
    private javax.swing.JRadioButton jRadioButtonSrednie;
    // End of variables declaration//GEN-END:variables
}
